/* Generated by Yosys 0.67+24 (git sha1 0e82bbefe, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 13.2.1) */

(* top =  1  *)
(* src = "alu_scan.v:23.1-112.10" *)
module alu_scan(clk, scan_enable, scan_in, A, B, opcode, scan_out, result);
  reg \$auto$verilog_backend.cc:2454:dump_module$25  = 0;
  (* src = "alu_scan.v:24.11-24.14" *)
  input clk;
  wire clk;
  (* src = "alu_scan.v:25.11-25.22" *)
  input scan_enable;
  wire scan_enable;
  (* src = "alu_scan.v:26.11-26.18" *)
  input scan_in;
  wire scan_in;
  (* src = "alu_scan.v:28.17-28.18" *)
  input [3:0] A;
  wire [3:0] A;
  (* src = "alu_scan.v:29.17-29.18" *)
  input [3:0] B;
  wire [3:0] B;
  (* src = "alu_scan.v:30.17-30.23" *)
  input [3:0] opcode;
  wire [3:0] opcode;
  (* src = "alu_scan.v:32.12-32.20" *)
  output scan_out;
  wire scan_out;
  (* src = "alu_scan.v:33.18-33.24" *)
  output [3:0] result;
  wire [3:0] result;
  (* src = "alu_scan.v:39.1-74.4" *)
  reg [3:0] _00_;
  (* src = "alu_scan.v:39.1-74.4" *)
  reg [3:0] _01_;
  (* src = "alu_scan.v:43.27-43.32" *)
  wire [3:0] _02_;
  (* src = "alu_scan.v:56.27-56.32" *)
  wire [31:0] _03_;
  (* src = "alu_scan.v:59.27-59.32" *)
  wire [31:0] _04_;
  (* src = "alu_scan.v:59.27-59.36" *)
  wire [31:0] _05_;
  (* src = "alu_scan.v:45.27-45.32" *)
  wire [3:0] _06_;
  (* src = "alu_scan.v:50.29-50.34" *)
  wire [3:0] _07_;
  (* src = "alu_scan.v:65.23-65.29" *)
  wire _08_;
  (* src = "alu_scan.v:62.23-62.28" *)
  wire _09_;
  (* src = "alu_scan.v:49.27-49.35" *)
  wire [3:0] _10_;
  (* src = "alu_scan.v:50.27-50.35" *)
  wire [3:0] _11_;
  (* src = "alu_scan.v:51.27-51.35" *)
  wire [3:0] _12_;
  (* src = "alu_scan.v:68.22-68.24" *)
  wire [3:0] _13_;
  (* src = "alu_scan.v:46.27-46.32" *)
  wire [3:0] _14_;
  (* src = "alu_scan.v:51.29-51.34" *)
  wire [3:0] _15_;
  (* src = "alu_scan.v:53.27-53.33" *)
  wire [3:0] _16_;
  (* src = "alu_scan.v:54.27-54.33" *)
  wire [3:0] _17_;
  (* src = "alu_scan.v:44.27-44.32" *)
  wire [3:0] _18_;
  (* src = "alu_scan.v:57.27-57.32" *)
  wire [31:0] _19_;
  (* src = "alu_scan.v:62.22-62.49" *)
  wire [3:0] _20_;
  (* src = "alu_scan.v:65.22-65.50" *)
  wire [3:0] _21_;
  (* src = "alu_scan.v:48.27-48.32" *)
  wire [3:0] _22_;
  (* src = "alu_scan.v:49.29-49.34" *)
  wire [3:0] _23_;
  (* src = "alu_scan.v:36.11-36.21" *)
  reg [3:0] alu_result;
  assign _02_ = A + (* src = "alu_scan.v:43.27-43.32" *) B;
  assign _03_ = A + (* src = "alu_scan.v:56.27-56.32" *) 32'd1;
  assign _04_ = A + (* src = "alu_scan.v:59.27-59.32" *) B;
  assign _05_ = _04_ + (* src = "alu_scan.v:59.27-59.36" *) 32'd1;
  assign _06_ = A & (* src = "alu_scan.v:45.27-45.32" *) B;
  assign _07_ = A & (* src = "alu_scan.v:50.29-50.34" *) B;
  assign _08_ = A == (* src = "alu_scan.v:65.23-65.29" *) B;
  assign _09_ = A > (* src = "alu_scan.v:62.23-62.28" *) B;
  assign _10_ = ~ (* src = "alu_scan.v:49.27-49.35" *) _23_;
  assign _11_ = ~ (* src = "alu_scan.v:50.27-50.35" *) _07_;
  assign _12_ = ~ (* src = "alu_scan.v:51.27-51.35" *) _15_;
  assign _13_ = ~ (* src = "alu_scan.v:68.22-68.24" *) A;
  assign _14_ = A | (* src = "alu_scan.v:46.27-46.32" *) B;
  assign _15_ = A | (* src = "alu_scan.v:51.29-51.34" *) B;
  assign _16_ = A << (* src = "alu_scan.v:53.27-53.33" *) 32'd1;
  assign _17_ = A >> (* src = "alu_scan.v:54.27-54.33" *) 32'd1;
  assign _18_ = A - (* src = "alu_scan.v:44.27-44.32" *) B;
  assign _19_ = A - (* src = "alu_scan.v:57.27-57.32" *) 32'd1;
  assign _20_ = _09_ ? (* src = "alu_scan.v:62.22-62.49" *) 4'h1 : 4'h0;
  assign _21_ = _08_ ? (* src = "alu_scan.v:65.22-65.50" *) 4'h1 : 4'h0;
  assign _22_ = A ^ (* src = "alu_scan.v:48.27-48.32" *) B;
  assign _23_ = A ^ (* src = "alu_scan.v:49.29-49.34" *) B;
  (* module_not_derived = 32'd1 *)
  (* src = "alu_scan.v:78.10-84.2" *)
  scan_dff FF0 (
    .clk(clk),
    .d(alu_result[0]),
    .q(result[0]),
    .scan_enable(scan_enable),
    .scan_in(scan_in)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "alu_scan.v:86.10-92.2" *)
  scan_dff FF1 (
    .clk(clk),
    .d(alu_result[1]),
    .q(result[1]),
    .scan_enable(scan_enable),
    .scan_in(result[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "alu_scan.v:94.10-100.2" *)
  scan_dff FF2 (
    .clk(clk),
    .d(alu_result[2]),
    .q(result[2]),
    .scan_enable(scan_enable),
    .scan_in(result[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "alu_scan.v:102.10-108.2" *)
  scan_dff FF3 (
    .clk(clk),
    .d(alu_result[3]),
    .q(result[3]),
    .scan_enable(scan_enable),
    .scan_in(result[2])
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2454:dump_module$25 ) begin end
    _00_ = _01_;
    (* src = "alu_scan.v:41.5-73.12" *)
    casez (opcode)
      /* src = "alu_scan.v:41.17-41.17" */
      4'h0:
          _01_ = _02_;
      /* src = "alu_scan.v:43.33-43.33" */
      4'h1:
          _01_ = _18_;
      /* src = "alu_scan.v:44.33-44.33" */
      4'h2:
          _01_ = _06_;
      /* src = "alu_scan.v:45.33-45.33" */
      4'h3:
          _01_ = _14_;
      /* src = "alu_scan.v:46.33-46.33" */
      4'h4:
          _01_ = _22_;
      /* src = "alu_scan.v:48.33-48.33" */
      4'h5:
          _01_ = _10_;
      /* src = "alu_scan.v:49.36-49.36" */
      4'h6:
          _01_ = _11_;
      /* src = "alu_scan.v:50.36-50.36" */
      4'h7:
          _01_ = _12_;
      /* src = "alu_scan.v:51.36-51.36" */
      4'h8:
          _01_ = _16_;
      /* src = "alu_scan.v:53.34-53.34" */
      4'h9:
          _01_ = _17_;
      /* src = "alu_scan.v:54.34-54.34" */
      4'ha:
          _01_ = _03_[3:0];
      /* src = "alu_scan.v:56.33-56.33" */
      4'hb:
          _01_ = _19_[3:0];
      /* src = "alu_scan.v:57.33-57.33" */
      4'hc:
          _01_ = _05_[3:0];
      /* src = "alu_scan.v:59.37-59.37" */
      4'hd:
          _01_ = _20_;
      /* src = "alu_scan.v:62.50-62.50" */
      4'he:
          _01_ = _21_;
      /* src = "alu_scan.v:65.51-65.51" */
      4'hf:
          _01_ = _13_;
      /* src = "alu_scan.v:68.25-68.25" */
      default:
          _01_ = 4'h0;
    endcase
  end
  always @* begin
      alu_result <= _00_;
  end
  assign scan_out = result[3];
endmodule

(* src = "scan_dff.v:23.1-39.10" *)
module scan_dff(clk, d, scan_in, scan_enable, q);
  reg \$auto$verilog_backend.cc:2454:dump_module$26  = 0;
  (* src = "scan_dff.v:24.11-24.14" *)
  input clk;
  wire clk;
  (* src = "scan_dff.v:25.11-25.12" *)
  input d;
  wire d;
  (* src = "scan_dff.v:26.11-26.18" *)
  input scan_in;
  wire scan_in;
  (* src = "scan_dff.v:27.11-27.22" *)
  input scan_enable;
  wire scan_enable;
  (* src = "scan_dff.v:28.16-28.17" *)
  output q;
  reg q;
  (* src = "scan_dff.v:31.1-37.4" *)
  reg _0_;
  always @* begin
    if (\$auto$verilog_backend.cc:2454:dump_module$26 ) begin end
    _0_ = q;
    (* src = "scan_dff.v:33.5-36.16" *)
    if (scan_enable) begin
      _0_ = scan_in;
    end else begin
      _0_ = d;
    end
  end
  always @(posedge clk) begin
      q <= _0_;
  end
endmodule
